### ISSUE TITLE
AssertionError:     assert len(data) > 0

### ISSUE THREAD

**Issue by sirspock** [Mirantis/disk_perf_test_tool#14]
Hi 

I'm having a problem running the following test.
```
include: default.yaml
explicit_nodes:
    local: testnode
tests:
    - io:
        cfg: hdd
        params:
            NUM_ROUNDS: 1
            FILENAME: /mnt/test.raw
            TEST_FILE_SIZE: 20G
```
Software installed:
- CentOS Linux release 7.2.1511 (Core)
- fio-2.2.8-2.el7.x86_64

Error:
```
21:06:03 - DEBUG    - wally           - Test on node 127.0.0.1 is finished
21:06:03 - ERROR    - wally           - During run_tests_stage
Traceback (most recent call last):
  File "wally/main.py", line 125, in log_stage
    yield
  File "wally/main.py", line 277, in main
    stage(cfg, ctx)
  File "wally/run_test.py", line 481, in run_tests_stage
    for tp, res in run_tests(cfg, test_group, ctx.nodes):
  File "wally/run_test.py", line 242, in run_tests
    res = test_cls(test_cfg).run()
  File "wally/suits/io/fio.py", line 765, in run
    res = load_test_results(self.config.log_directory, pos)
  File "wally/suits/io/fio.py", line 131, in load_test_results
    ts = load_sys_log_file(ftype, os.path.join(folder, fname))
  File "wally/suits/io/fio.py", line 89, in load_sys_log_file
    return TimeSeriesValue(vals)
  File "wally/suits/itest.py", line 116, in __init__
    assert len(data) > 0
AssertionError
```
Can you give me a hand?
Thanks a lot.

**Comment by koder-ua** [comment]
That mean, that for some reason fio does return an empty report, or there some bug in wally or paramiko,
which result in losing fio output. I have seen such issue several times but was unable to fix it in v1. I suggest you rerun test, usually this issue doesn't reproduce. Meanwhile if you are using slow vm's to run a test you might face it often. 

It should be completely fixed in v2.0 branch, but it's not yet stable
